## Data Cleaning

### 1. Project Objective

The purpose of this notebook is to improve data quality and prepare the dataset for exploratory data analysis.

The cleaning process includes:

- Assessing data quality
- Correcting data types
- Creating useful features
- Exporting a cleaned dataset

### 2. Import Libraries

In [1]:
import pandas as pd
import numpy as np

### 3. Load Raw Dataset

In [2]:
df = pd.read_csv("../data/raw/Superstore.csv", encoding="ISO-8859-1")
df.head(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2013-138688,13-06-2013,17-06-2013,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2012-108966,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2012-108966,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

### 4. Assess Data Quality

#### 4.1 Missing Values

In [3]:
missing = df.isna().sum()
missing

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [4]:
missing[missing > 0]

Series([], dtype: int64)

No missing values were found.

#### 4.2 Duplicate Records

In [5]:
df.duplicated().sum()

np.int64(0)

No duplicate records were found.

#### 4.3 Data Types

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

Order Date and Ship Date are stored as object and need to be converted to datetime.

#### 4.4 Numeric Columns

In [7]:
numeric_columns = [
    "Sales",
    "Quantity",
    "Discount",
    "Profit"
]

df[numeric_columns].dtypes

Sales       float64
Quantity      int64
Discount    float64
Profit      float64
dtype: object

### 5. Clean Data

#### 5.1 Convert Date Columns

In [8]:
df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    format = '%d-%m-%Y'
)

df["Ship Date"] = pd.to_datetime(
    df["Ship Date"],
    format = '%d-%m-%Y'
)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 1.6+ MB

#### 5.2 Standardize Data Types

In [10]:
df["Postal Code"] = df["Postal Code"].astype("string")

In [11]:
df["Postal Code"].dtype

string[python]

#### 5.3 Create New Features

In [12]:
# Year
df["Year"] = df["Order Date"].dt.year

# Month
df["Month"] = df["Order Date"].dt.month

# Month Name
df["Month Name"] = df["Order Date"].dt.month_name()

# Quarter
df["Quarter"] = df["Order Date"].dt.quarter

# Weekday
df["Weekday"] = df["Order Date"].dt.day_name()

In [13]:
# Shipping Days
df["Shipping Days"] = (
    df["Ship Date"]
    - df["Order Date"]
).dt.days

In [14]:
# Profit Margin
df["Profit Margin"] = np.where(
    df["Sales"] != 0,
    df["Profit"] / df["Sales"],
    np.nan
)

In [15]:
df.head(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Quantity,Discount,Profit,Year,Month,Month Name,Quarter,Weekday,Shipping Days,Profit Margin
0,1,CA-2013-152156,2013-11-09,2013-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,2,0.00,41.9136,2013,11,November,4,Saturday,3,0.1600
1,2,CA-2013-152156,2013-11-09,2013-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,3,0.00,219.5820,2013,11,November,4,Saturday,3,0.3000
2,3,CA-2013-138688,2013-06-13,2013-06-17,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,2,0.00,6.8714,2013,6,June,2,Thursday,4,0.4700
3,4,US-2012-108966,2012-10-11,2012-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,5,0.45,-383.0310,2012,10,October,4,Thursday,7,-0.4000
4,5,US-2012-108966,2012-10-11,2012-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,2,0.20,2.5164,2012,10,October,4,Thursday,7,0.1125

### 6. Validate Cleaned Data

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 28 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   string
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
 21  Year           9994 non-null   int32
 22  Month          9994 non-null   int32
 23  Month Name     9994 non-null   object
 24  Quarter        9994 non-null   int32
 25  Weekday        9994 non-null   object
 26  Shipping Days  9994 non-null   int64
 27  Profit Margin  9994 non-null   float64
dtypes: datetime64[ns](2), float64(4), int32(3), int64(3), object(15), string(1)
memory usage: 2.0+ MB

In [19]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
Row ID,9994.0,4997.5,1.0,2499.25,4997.5,7495.75,9994.0,2885.163629
Order Date,9994,2013-04-30 19:20:02.401441024,2011-01-04 00:00:00,2012-05-23 00:00:00,2013-06-27 00:00:00,2014-05-15 00:00:00,2014-12-31 00:00:00,NaN
Ship Date,9994,2013-05-04 18:20:49.229537792,2011-01-08 00:00:00,2012-05-27 00:00:00,2013-06-30 00:00:00,2014-05-19 00:00:00,2015-01-06 00:00:00,NaN
Sales,9994.0,229.858001,0.444,17.28,54.49,209.94,22638.48,623.245101
Quantity,9994.0,3.789574,1.0,2.0,3.0,5.0,14.0,2.22511
Discount,9994.0,0.156203,0.0,0.0,0.2,0.2,0.8,0.206452
Profit,9994.0,28.656896,-6599.978,1.72875,8.6665,29.364,8399.976,234.260108
Year,9994.0,2012.722934,2011.0,2012.0,2013.0,2014.0,2014.0,1.124039
Month,9994.0,7.814589,1.0,5.0,9.0,11.0,12.0,3.286047
Quarter,9994.0,2.88413,1.0,2.0,3.0,4.0,4.0,1.056771
Shipping Days,9994.0,3.958875,0.0,3.0,4.0,5.0,7.0,1.747097
Profit Margin,9994.0,0.120314,-2.75,0.075,0.27,0.3625,0.5,0.466754

### 7. Export Clean Dataset

In [20]:
df.to_csv(
    "../data/processed/superstore_clean.csv",
    index=False
)

The cleaned dataset has been exported successfully and will be used for subsequent exploratory data analysis.